services:
  app-cpu:
    build:
      context: .
      args:
        - BASE_IMAGE=ubuntu:22.04
        - TARGET=cpu
    image: ccardina/app2:cpu
  
  app-gpu:
    build:
      context: .
      args:
        - BASE_IMAGE=nvidia/cuda:12.1.1-devel-ubuntu22.04
        - TARGET=gpu
    image: ccardina/app2:gpu
